/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SolicitudResponse
 */
@JsonPropertyOrder({
  SolicitudResponse.JSON_PROPERTY_DONE,
  SolicitudResponse.JSON_PROPERTY_TOKEN_SOLICITUD,
  SolicitudResponse.JSON_PROPERTY_ERROR_MESSAGE,
  SolicitudResponse.JSON_PROPERTY_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-23T03:09:46.344348+02:00[Europe/Madrid]", comments = "Generator version: 7.8.0")
public class SolicitudResponse {
  public static final String JSON_PROPERTY_DONE = "done";
  private Boolean done;

  public static final String JSON_PROPERTY_TOKEN_SOLICITUD = "tokenSolicitud";
  private Integer tokenSolicitud;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  private JsonNullable<String> errorMessage = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DATA = "data";
  private Boolean data;

  public SolicitudResponse() {
  }

  public SolicitudResponse done(Boolean done) {
    
    this.done = done;
    return this;
  }

  /**
   * Get done
   * @return done
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDone() {
    return done;
  }


  @JsonProperty(JSON_PROPERTY_DONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDone(Boolean done) {
    this.done = done;
  }

  public SolicitudResponse tokenSolicitud(Integer tokenSolicitud) {
    
    this.tokenSolicitud = tokenSolicitud;
    return this;
  }

  /**
   * Get tokenSolicitud
   * @return tokenSolicitud
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOKEN_SOLICITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTokenSolicitud() {
    return tokenSolicitud;
  }


  @JsonProperty(JSON_PROPERTY_TOKEN_SOLICITUD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTokenSolicitud(Integer tokenSolicitud) {
    this.tokenSolicitud = tokenSolicitud;
  }

  public SolicitudResponse errorMessage(String errorMessage) {
    this.errorMessage = JsonNullable.<String>of(errorMessage);
    
    return this;
  }

  /**
   * Get errorMessage
   * @return errorMessage
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getErrorMessage() {
        return errorMessage.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getErrorMessage_JsonNullable() {
    return errorMessage;
  }
  
  @JsonProperty(JSON_PROPERTY_ERROR_MESSAGE)
  public void setErrorMessage_JsonNullable(JsonNullable<String> errorMessage) {
    this.errorMessage = errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = JsonNullable.<String>of(errorMessage);
  }

  public SolicitudResponse data(Boolean data) {
    
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(Boolean data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SolicitudResponse solicitudResponse = (SolicitudResponse) o;
    return Objects.equals(this.done, solicitudResponse.done) &&
        Objects.equals(this.tokenSolicitud, solicitudResponse.tokenSolicitud) &&
        equalsNullable(this.errorMessage, solicitudResponse.errorMessage) &&
        Objects.equals(this.data, solicitudResponse.data);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(done, tokenSolicitud, hashCodeNullable(errorMessage), data);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SolicitudResponse {\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("    tokenSolicitud: ").append(toIndentedString(tokenSolicitud)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

